export const recipesMockData = [
  {
    name: "Spaghetti Carbonara",
    category: "Pasta",
    emoji: "🍝",
    prepTime: "30 minutos",
    difficulty: "Media",
    ingredients: ["Spaghetti", "Eggs", "Pancetta", "Parmesan Cheese"],
    steps: [
      "Cocina el spaghetti en agua con sal.",
      "Sofrie la pancetta hasta que este dorada.",
      "Mezcla los huevos con el queso parmesano.",
      "Integra la pasta con la mezcla fuera del fuego.",
    ],
  },
  {
    name: "Chicken Tacos",
    category: "Plato fuerte",
    emoji: "🌮",
    prepTime: "25 minutos",
    difficulty: "Facil",
    ingredients: ["Tortillas", "Chicken", "Onion", "Tomato", "Lettuce"],
    steps: [
      "Sazona y cocina el pollo.",
      "Calienta las tortillas en una sarten.",
      "Arma los tacos con vegetales frescos.",
      "Sirve con salsa y limon.",
    ],
  },
  {
    name: "Sopa de Tomate",
    category: "Entrada",
    emoji: "🍅",
    prepTime: "35 minutos",
    difficulty: "Facil",
    ingredients: ["Tomates", "Cebolla", "Ajo", "Caldo de verduras", "Crema"],
    steps: [
      "Sofrie cebolla y ajo en una olla.",
      "Agrega tomates y cocina 10 minutos.",
      "Incorpora el caldo y cocina a fuego medio.",
      "Licua la mezcla y sirve con crema.",
    ],
  },
  {
    name: "Arroz con Pollo",
    category: "Plato fuerte",
    emoji: "🍚",
    prepTime: "50 minutos",
    difficulty: "Media",
    ingredients: ["Arroz", "Pollo", "Pimenton", "Arvejas", "Caldo de pollo"],
    steps: [
      "Dora el pollo con condimentos.",
      "Agrega vegetales y sofrie brevemente.",
      "Incorpora arroz y caldo.",
      "Cocina hasta que el arroz este listo.",
    ],
  },
  {
    name: "Panqueques",
    category: "Desayuno",
    emoji: "🥞",
    prepTime: "20 minutos",
    difficulty: "Facil",
    ingredients: ["Harina", "Huevos", "Leche", "Mantequilla", "Azucar"],
    steps: [
      "Mezcla harina, huevos y leche.",
      "Agrega mantequilla derretida.",
      "Cocina porciones en sarten caliente.",
      "Sirve con fruta o miel.",
    ],
  },
  {
    name: "Limonada de Hierbabuena",
    category: "Bebida",
    emoji: "🍋",
    prepTime: "10 minutos",
    difficulty: "Facil",
    ingredients: ["Limon", "Agua", "Azucar", "Hierbabuena", "Hielo"],
    steps: [
      "Exprime los limones.",
      "Licua jugo, agua, azucar y hierbabuena.",
      "Cuela si lo prefieres.",
      "Sirve con hielo.",
    ],
  },
]
